"""One-time setup — creates the Managed Agent and Cloud Environment on Claude platform.

Run once:
    uv run python setup_agent.py

Copy the printed IDs into .env (or append them automatically via the --write flag).
"""

import argparse
import os
import sys

import anthropic
from dotenv import load_dotenv

from claude_forex_agent.tools.registry import TOOL_SCHEMAS

load_dotenv()

SYSTEM_PROMPT = """You are a foreign exchange (forex) analyst assistant.
You help users understand currency markets, exchange rates, and FX strategies.
Use the available tools to fetch live data before answering quantitative questions.
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Create Managed Agent and Environment.")
    parser.add_argument(
        "--write",
        action="store_true",
        help="Append the generated IDs directly to .env",
    )
    args = parser.parse_args()

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("Error: ANTHROPIC_API_KEY is not set. Add it to .env first.")
        sys.exit(1)

    client = anthropic.Anthropic(api_key=api_key)

    print("Creating cloud environment…")
    env = client.beta.environments.create(
        name="forex-agent-env",
        config={"type": "cloud", "networking": {"type": "unrestricted"}},
    )
    print(f"  Environment ID: {env.id}")

    print("Creating Managed Agent with forex tools…")
    custom_tools = [{"type": "custom", **schema} for schema in TOOL_SCHEMAS]
    agent = client.beta.agents.create(
        name="Claude Forex Agent",
        model="claude-opus-4-8",
        system=SYSTEM_PROMPT,
        tools=custom_tools,
    )
    print(f"  Agent ID:      {agent.id}")
    print(f"  Agent version: {agent.version}")

    lines = [
        "",
        "# Managed Agent (generated by setup_agent.py — do not commit)",
        f"MANAGED_AGENT_ID={agent.id}",
        f"MANAGED_AGENT_VERSION={agent.version}",
        f"MANAGED_AGENT_ENV_ID={env.id}",
    ]

    if args.write:
        with open(".env", "a") as f:
            f.write("\n".join(lines) + "\n")
        print("\nIDs appended to .env.")
    else:
        print("\nAdd these lines to your .env file:")
        for line in lines:
            print(line)


if __name__ == "__main__":
    main()
